// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKG_9Cr6n7HvaaipC4gw5opw9NDA_3GBo',
    appId: '1:543005834254:web:e3a2651606084c7c2e905f',
    messagingSenderId: '543005834254',
    projectId: 'my-chat-app1',
    authDomain: 'my-chat-app1-246c2.firebaseapp.com',
    storageBucket: 'my-chat-app1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQjmC65GjUImxkDhgsQNIlnEuoMxixuW0',
    appId: '1:543005834254:android:b3913a6b537b2ace2e905f',
    messagingSenderId: '543005834254',
    projectId: 'my-chat-app1',
    storageBucket: 'my-chat-app1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8BJloSHzo_nwIC2KaQ_FZCgFGjYu9YJA',
    appId: '1:543005834254:ios:90bec1d69d0fa37d2e905f',
    messagingSenderId: '543005834254',
    projectId: 'my-chat-app1',
    storageBucket: 'my-chat-app1.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8BJloSHzo_nwIC2KaQ_FZCgFGjYu9YJA',
    appId: '1:543005834254:ios:77d84a7ae79af1fc2e905f',
    messagingSenderId: '543005834254',
    projectId: 'my-chat-app1',
    storageBucket: 'my-chat-app1.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
